<?php
require_once(ROOT_PATH."/vendor/autoload.php");
require_once(ROOT_PATH."/class/controllers/db.php");
require_once(ROOT_PATH."/class/controllers/Rights.php");
require_once(ROOT_PATH."/class/controllers/Federal.php");
require_once(ROOT_PATH."/class/controllers/global.php");
require_once(ROOT_PATH."/class/controllers/SessionHandler.php");
require_once(ROOT_PATH."/class/controllers/User.php");
require_once(ROOT_PATH."/class/controllers/School.php");
require_once(ROOT_PATH."/class/controllers/SchoolClass.php");
require_once(ROOT_PATH."/class/controllers/SchoolTemplateMap.php");
require_once(ROOT_PATH."/class/controllers/SchoolTemplate.php");
require_once(ROOT_PATH."/class/controllers/Student.php");
require_once(ROOT_PATH."/Modules/IModule.php");
require_once(ROOT_PATH."/Modules/Module.php");
require_once(ROOT_PATH."/Modules/ModuleLoader.php");
require_once(ROOT_PATH."/class/controllers/IPrintTemplate.php");
require_once(ROOT_PATH."/class/controllers/PrintTemplateModelAbstract.php");
require_once(ROOT_PATH."/class/controllers/SchoolTemplateVariable.php");
require_once(ROOT_PATH."/class/controllers/SchoolTemplateVariables.php");
?>